### PR TITLE
refactor(hooks): :zap: using `preLoadAddressDataFromUser` whenever user profile hook in used

### PR DESCRIPTION
**Pull request by lehuygiang28**

### CODE REVIEW

**Comment by lehuygiang28** [comment]
**[@Pullflow](https://app.pullflow.com)** is state of a hooks save in a components ?

**Comment by lehuygiang28** [comment]
**[@Pullflow](https://app.pullflow.com)** is state of a hooks save in a components ?

**Comment by lehuygiang28** [comment]
**[@Pullflow](https://app.pullflow.com)** what happen if use a hook in a hook ? is good or bad approach ?

**Comment by lehuygiang28** [comment]
@Pullflow can you conservation ?

**Review by techcellcloud — APPROVED** [review]

**Pull request merged**
